@startuml

class Image {
  +loadFromFile(filepath: string) : Image
  +saveToFile(filepath: string) : void
  +toGrayscale() : Image
}

interface IEdgeDetector {
  +detectEdges()
}

class SobelDetector {
  +detectEdges()
}

class PrewittDetector {
  +detectEdges()
}

IEdgeDetector <|-- SobelDetector
IEdgeDetector <|-- PrewittDetector

note right of Image : Image File I/O
note left of IEdgeDetector : Edge Detection Algorithm

@enduml
